### ISSUE TITLE
Limit the number of accuracy digits

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#100]
Please limit the number of digits!
```
"Photo (4.550999641418457m)"
"big turn (4.550999641418457m)"
```

**Comment by nguillaumin** [comment]
Can you give a bit more context? Where is that from?

Also, how many digits are "correct"? Is there actually a universal answer that will please all users (and that's not something that deserves an option IMHO).

**Comment by jidanni** [comment]
It is when saving a text note or photo.
It is added to the CDATA.
How about 0.1 meters at the most.

**Comment by nguillaumin** [comment]
> How about 0.1 meters at the most.

Ah, but I want 0.01 myself, and this other guys want 0.001...

I guess there's no point going below the GPS accuracy, not sure what that is these days.

**Comment by jidanni** [comment]
https://stackoverflow.com/questions/1567443/how-accurate-is-android-gps

**Comment by nguillaumin** [comment]
> something like 30% of your measurements within 50 meters of the true position

Hard to tell how that should translate to an accuracy measure in the GPX file, but I guess 0.1 or 0.1 would be good enough.

I'll take a patch for that if you're keen.
