### ISSUE TITLE
Feature Request: warn on low accuracy

### ISSUE THREAD

**Issue by Bibi56** [labexp/osmtracker-android#102]
Nice to have: indicate when the HDOP is bigger than a parameter setting (feeback: sound, notification, different style for the text...).

Why? If we want to take pictures, notes etc..., it's good to be aware of low accuracy.

**Comment by Binnette** [comment]
We already have accuracy display on the main screen, so I don't see the point.
Also I don't want to show an extra annoying toast/popup.
Feel free to reopen the bug if needed.
