### ISSUE TITLE
"uploaded" icon disappears when scrolling

### ISSUE THREAD

**Issue by nicolas-raoul** [labexp/osmtracker-android#113]
Steps:
1. Have a lot of tracks (I have about 20)
2. Upload a few of them. They get a ↑ icon which means they have been uploaded, if I understand correctly
3. Scroll up and down a few times
4. Some of the ↑ icons have disappeared, so I can not tell anymore what tracks I have uploaded already.

Workaround: Pretending to upload a file then pressing "Back" to cancel makes the  ↑ icons reappear.

**Comment by jfburke3** [comment]
I have this happen, too, on two different phones (Samsung Galaxy S7 Edge running Android 7.0, and Samsung Galaxy S5 Active, running Android 6.0.1).

**Comment by nguillaumin** [comment]
Probably some legacy bug in an older Android component we use that's not working well on newer Android phones... But TBH I'm unlikely to fix it since I don't really work on the app. anymore...

**Comment by jamescr** [comment]
Fixed in the next app version.
