### ISSUE TITLE
Colocar un mensaje cuando se esté actualizando un layout

### ISSUE THREAD

**Issue by altaros97** [labexp/osmtracker-android#115]
En la opción <code>Update and Install</code> se debería colocar como un <code>updating</code> cuando se esté ejecutando la funcionalidad

**Comment by EmmanuelAB** [comment]
ya hay algo similar en el PR #119, voy a poner lo que pide este issue en ese PR

**Comment by jamescr** [comment]
¿Esto ya se puede cerrar?

**Comment by EmmanuelAB** [comment]
Ya entró el PR que cierra este issue
