### ISSUE TITLE
Show how many points have already been collected during collection

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#121]
Made me some indication should be given to the user about how many points have already been collected *during* collection.

**Comment by EmmanuelAB** [comment]
Hi, we think the inferface shown during collection has enough elements to think in adding more. By the way, when tracking you can press `back` to go to the list of tracks and then, you can see the number of collected waypoints/trackpoints. Thanks.

**Comment by jidanni** [comment]
OK. By the way, the user does not dare to press Back because in other programs that often throws away all his work.
