### ISSUE TITLE
Cycle map says API key required

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#125]
Cycle map background map says API key required in a watermark on top of the map.

**Comment by nguillaumin** [comment]
I guess they've changed and now require an API key. Someone will have to implement support for this, either by hardcoding an API key in the app. or by allowing the user to enter one.

**Comment by xsaco07** [comment]
Hi, this issue was fixed in the PR #203
The problem basically was that the storage permissions weren't asked properly and if the user didn't grant them the display of the background map failed, regardless of the map tile source.

**Comment by EmmanuelAB** [comment]
Now the app can only use Mapnik as tile provider (since it's the only working without a key). Then Cycle Map is not even choosable. This issue will be closed.
