### ISSUE TITLE
MapQuest Open background map is all white.

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#127]
MapQuest Open background map is all white.

**Comment by tuxayo** [comment]
Aren't the MapQuest tiles not available anymore since few years?

**Comment by xsaco07** [comment]
Hi, this issue was fixed in the PR #203 
The problem basically was that the storage permissions weren't asked properly and if the user didn't grant them the display of the background map failed, regardless of the map tile source.
