### ISSUE TITLE
JOSM compatible audio

### ISSUE THREAD

**Issue by fschlich** [labexp/osmtracker-android#134]
I like to process my tracks with JOSM. Unfortunately it doesn't know how to deal with 3gpp audio and will open a browser when clicking on an audio note. It can deal with WAV though and perhaps mp3. Could you add an option to save the audio as WAV please?

**Comment by fschlich** [comment]
BTW this goes back a few years:
https://josm.openstreetmap.de/ticket/11017 from 2015
https://josm.openstreetmap.de/ticket/5805 from 2011
So this seems to be hard to fix on the JOSM side ("OSM never had a real support of 3GP format and never will until Java itself supports it.")

**Comment by magol** [comment]
For me, josm open the audio in VLC, so I guess that you have to fix the file association in windows.

**Comment by fschlich** [comment]
It's Debian GNU/Linux actually, but opening an external application for a 3-seconds audio note feels clumsy even if it's an application that will actually play the audio. My assumption was that it should be easy to record "raw audio == WAV" instead of 3gpp, but I'm not very familiar with Android so this may not be the case.

**Comment by magol** [comment]
Aaah, then I understand. Yes, I agree that it should be handled internal in JOSM or that OSM Tracker should be recording in another audio format that JSOM support.

**Comment by stoecker** [comment]
According to the docs MediaRecorder class supports .wav, so a change should be easy by simply changing the output format of the recorder. JOSM supports Standard .wav files.

**Comment by mnalis** [comment]
In the meantime, script at https://github.com/labexp/osmtracker-android/wiki/Reading-3GPP-files to convert to `.wav` and update `.gpx`  seems like useful workaround

**Comment by Binnette** [comment]
JOSM is now capable of opening audio file (via VLC or something else)
