### ISSUE TITLE
Crash due to IllegalArgumentException: Unknown URI

### ISSUE THREAD

**Issue by tuxayo** [labexp/osmtracker-android#141]
java.lang.IllegalArgumentException: Unknown URI: content://me.guillaumin.android.osmtracker.provider/track/-1/trackpoints

(track -1 ???)

It crashed when switched to the app. Recording was on.

On a Moto G3 (X1541) with Android 7.1.2 (LineageOS for microG 14.1)

Could be related to #135

[logcat.txt](https://github.com/labexp/osmtracker-android/files/2075210/logcat.txt)

**Comment by aton1698** [comment]
Do you still have the same bug with the last release?
