### ISSUE TITLE
Tiny icons in custom layout

### ISSUE THREAD

**Issue by notpokey** [labexp/osmtracker-android#145]
I've made a custom layout, but all the icons are too small to see.
I'm using the icons from the source page, but I've renamed them. I don't see how that would make any difference.
![screenshot_20180705-190912](https://user-images.githubusercontent.com/15833248/42352242-29b9d352-8087-11e8-838b-3cc99faa5267.png)

**Comment by jamescr** [comment]
Could you share us a link to your custom layout?

**Comment by notpokey** [comment]
Yes, sorry.
https://pastebin.com/Fgv0FU03 (portrait)
https://pastebin.com/i99dihPg (landscape)

BTW, these buttons are VERY useful here in the US. I shared these config files with a couple of my friends, and we are all MUCH more productive at collecting useful traces. Please feel free to use or share them.

**Comment by aton1698** [comment]
It's because the size of the image. We recommend you to use 500 x 500 images. Android can resize the source images, that's why that ones works in the default layout.
Also, you can fallow [this structure](https://github.com/labexp/osmtracker-android-layouts/wiki), make a PR in the [custom layouts repository](https://github.com/labexp/osmtracker-android-layouts) and your custom layout will be available for everyone. :smiley:

**Comment by notpokey** [comment]
That might be just a little over my head, but for the sake of all humanity,
I will give it a try.

**Comment by aton1698** [comment]
[Here](https://github.com/jamescr/osmtracker-android-layouts/tree/notpokey_layout/layouts/notpokey) you can find an example. In case you don't understand how to do it, send us your icons ideas and we can try to help you!

**Comment by notpokey** [comment]
Anton, I'm only using the stock icons. They work just fine.

I'm using a custom layout that is more useful for logging speed limits,
road surfaces and access in the US.

The app didn't recognize when I specified the stock icons the way the
default layout does, so I made copies of them, but they are literally just
the stock icons.

**Comment by notpokey** [comment]
Than you! I will try to work on it this weekend.
