### ISSUE TITLE
Language cannot be changed

### ISSUE THREAD

**Issue by adrian7031** [labexp/osmtracker-android#146]
How can the language be changed? I cannot find any way. In the settings there is no choice. On my device it appears in German and I would like to change it to English.

**Comment by adam3497** [comment]
Hi @adrian7031 

Into the osmtracker app there isn't an option to change the language, this depends on the language of your phone.

**Comment by adam3497** [comment]
And @adrian7031 I forgot to mention that the new functionality of OSMTracker (v0.7) it is only in English and Spanish. for the moment.
