### ISSUE TITLE
Custom buttom file not working

### ISSUE THREAD

**Issue by adrian7031** [labexp/osmtracker-android#147]
I am trying to make a custom button file, but it always shows a parse error.
I started with the default file from GitHub, but that didn't work, so I have gradually reduced the content until I now have one root layout with one button, but I still get a parse error.
What could be the problem? Has the format changed? Where is the default file stored on the device?
In the source stored on GitHub I cannot fine the default icons, where are they?

**Comment by adam3497** [comment]
Hi @adrian7031 and thanks for waiting. 

There are two ways to make a custom button file. The most easy is create a file with the xml extenssion and put it into the osmtracker folder on your phone (this folder is in the SD Card and if you don't have any, in the internal memory), for that you can see [this wiki](https://github.com/labexp/osmtracker-android/wiki/Custom-buttons-layouts) where it is explained in more detail. 
 
The second option is to create a xml file and then upload to the [custom repository](https://github.com/labexp/osmtracker-android-layouts) making a pull request following this [structure](https://github.com/labexp/osmtracker-android-layouts/wiki).

Now, you are asking about the default icons, this icons are in the internal package of the app, so, the only thing that you need to do is put the name of the icon that you want, like this example: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<layouts>
	<layout name="root">
		<row>
			<button type="voicerec" icon="voice_32x32" />
			<button type="picture" icon="camera_32x32" />
			<button type="textnote" icon="text_32x32" />
		</row>
	</layout>
</layouts>
```

There are only three default icons (textnote, picture and voicerec). 

If you want to put some icon for your custom button you need to put it in a folder and then put the reference in the code:

```xml
<row>
	<button type="tag" label="Parada de Bus - Tipo 1" icon="/transporte_publico_icons/parada_bus_1.png" />
	<button type="tag" label="Parada de Bus - Tipo 2" icon="/transporte_publico_icons/parada_bus_2.png" />
	<button type="tag" label="Parada de Bus - Tipo 3" icon="/transporte_publico_icons/parada_bus_3.png" />
</row>
```

I hope this help you and I will be waiting for your answer!

**Comment by adam3497** [comment]
Hi again @adrian7031 

Could you solve the problem with the custom button file?

**Comment by adrian7031** [comment]
Yes, thank you. I have got everything to work. The first time I was transferring the file via FTP, I think the file was being corrupted. Now I transferred it with the windows explorer and it worked.

 

Adrian

 

Von: José Adrián Amador Ávila [mailto:notifications@github.com] 
Gesendet: Dienstag, 21. August 2018 19:28
An: labexp/osmtracker-android
Cc: adrian7031; Mention
Betreff: Re: [labexp/osmtracker-android] Custom buttom file not working (#147)

 

Hi again @adrian7031 <https://github.com/adrian7031> 

Could you solve the problem with the custom button file?
