### ISSUE TITLE
Unable to authenticate in OSM

### ISSUE THREAD

**Issue by jjiglesiasg** [labexp/osmtracker-android#152]
This happen again even that I deleted and uploaded the app twice in my S5. Service provider responded in error: 500 (Internal Server Error)

**Comment by adam3497** [comment]
Hi @jjiglesiasg 

What version of OSMTracker are you trying to use?

**Comment by jjiglesiasg** [comment]
The version is v0.6.11

**Comment by jamescr** [comment]
> The version is v0.6.11

[That bug](https://github.com/labexp/osmtracker-android/issues/137) is fixed in version 0.6.12 or latter.
