### ISSUE TITLE
Doesn't work in background 

### ISSUE THREAD

**Issue by FliegendeWurst** [labexp/osmtracker-android#158]
It used to keep recording in the background (0.6.11). I'm using a Huawei P8 Lite.

**Comment by adam3497** [comment]
Hi @haggaie 

Are you using the v0.6.11 or the current version (v0.7)?

**Comment by FliegendeWurst** [comment]
It worked in 0.6.11 and doesn't in 0.7.

**Comment by adam3497** [comment]
What is the android version of your phone?
