### ISSUE TITLE
Cannot upload track to OSM - app stops working

### ISSUE THREAD

**Issue by Halloway66** [labexp/osmtracker-android#159]
I select a track, then from the drop down menu select 'OpenStreetMap upload.'

I see the Exporting progress bar, then the Sending progress bar, then very briefly I see a 'Waiting for OpenStreetMap server response' message, then I get an error message "OSMTracker for Android has stopped" with the options to close app or send feedback. The track is not uploaded to OSM. 

OSMTracker v0.6.11 running on a Moto G4 with Android 7.0

**Comment by Halloway66** [comment]
I've just exported and downloaded the .gpx file and it is empty! I can display the track on the map in OSMTracker so obviously the data is there but perhaps the problem is that the export to .gpx function in the app is broken?

**Comment by aton1698** [comment]
That's a bug in that version, you can download the last version available on [F-Droid](https://f-droid.org/es/packages/net.osmtracker/) or [Play Store](https://play.google.com/store/apps/details?id=net.osmtracker).
If you have other issue, let us know! :)
