### ISSUE TITLE
Transifex ownership

### ISSUE THREAD

**Issue by nguillaumin** [labexp/osmtracker-android#160]
Hi there,

When I transferred the project to you guys I also transferred the Transifex project for the translations, but it seems I've been retaining control of some of the languages.

I would like to transfer that to, but to do that I need to name someone coordinator for these languages (as it needs at least one coordinator for each language).

Who should I name?

Thank you,

Nico

**Comment by adam3497** [comment]
Hi @nguillaumin 

I apologize for answering so far, but I was a little busy with several jobs at the university.

You can name me as coordinator if you want, you just have to explain what I have to do.

Thank you,

Adrián.

**Comment by adam3497** [comment]
I just tried to assign myself as coordinator of the language and yes, it is possible. So, should I do it with the other languages?

**Comment by nguillaumin** [comment]
Yes, if you could that'd be great, or at least for the languages when I'm the sole coordinator. Then I'll be able to leave the team (actually, you can even delete me from the team yourself I believe). Thanks!

**Comment by adam3497** [comment]
I appointed myself as coordinator of some languages ​​(like those who didn't have one) also I eliminated you from the languages ​​in which you were alone and I placed myself.

I believe that all it's done.

**Comment by nguillaumin** [comment]
Thanks, it looks like it worked as I'm not part of the project anymore. Cheers!
