### ISSUE TITLE
use GPX name for containing directory as well

### ISSUE THREAD

**Issue by PontiacCZ** [labexp/osmtracker-android#161]
Please add possibility to name the containing directory with the track's name when chosen "One directory per track".

I archive my tracks. The directories names are constructed using date and time in ISO-like manner which is good but I get directory named e.g. "2018-10-06_08-14-24" (see the screenshot). When I transfer the directory to my PC I need to manually append its name with the track's name so that it becomes self-descriptive in my archive. (like "2018-10-06_08-14-24_Prace_u_hřbitova")

![obrazek](https://user-images.githubusercontent.com/9153595/46796072-fd41f680-cd4b-11e8-9d59-7b3b388d31ee.png)

When I'm looking at the screenshot now I realize it would be useful first to be able to use the ISO-date style with the initial track naming. I sure can overwrite it everytime in OSMTracker but typing special chars like hyphens and underscores is inconvenient on the phone display. I'l file a separate issue for that...

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #161 - Consistency of trace files names](https://trello.com/c/26vNskWm/40-issue-161-consistency-of-trace-files-names)

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #161 - Consistency of trace files names](https://trello.com/c/26vNskWm/40-issue-161-consistency-of-trace-files-names)

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use GPX name for containing directory as well](https://trello.com/c/7AjJQCN3/41-use-gpx-name-for-containing-directory-as-well)

**Comment by EmmanuelAB** [comment]
Something like #230 ?

**Comment by aton1698** [comment]
This issue is solved with #230 and #232
