### ISSUE TITLE
map view: names unreadable

### ISSUE THREAD

**Issue by PontiacCZ** [labexp/osmtracker-android#164]
This is how map view looks like in the closest zoom on my  Nexus 6:

![obrazek](https://user-images.githubusercontent.com/9153595/47152097-fed76580-d2db-11e8-9b5c-b56bffe3219f.png)

The names of the streets and building are simply unreadable so I don't know whether they are correct or they need updating. I cannot zoom in anymore to get them bigger.

Mapnik on PC (www.openstreetmap.org) is readable without problems. Most likely this is related to display DPI but I could not find any option in the settings regarding DPI.

**Comment by EmmanuelAB** [comment]
The solution to this issue will be included in the next release 0.7.2.
