### ISSUE TITLE
GPX file failed to import in Open StreetMap

### ISSUE THREAD

**Issue by hikaruAi** [labexp/osmtracker-android#167]
The message i get when i upload a trace:

> Hi,

>It looks like your GPX file

>  osm_upload201855087.gpx

>with the description

  >juan

>and the following tags:

>  osmtracker

>failed to import. Here's the error:

```
  Unable to read data from /store/rails/gpx/traces/2829773.gpx (errno=Success)
  XML parser at line 0 column 0
```

>More information about GPX import failures and how to avoid
>them can be found at:

**Comment by marcelvb** [comment]
Same issue here.

**Comment by MattCost** [comment]
Go to Settings > App s & Notifications > App Permissions >  Storage > OSMTracker and enable the permission.

It seems the app does not ASK for storage permissions in the app directly.

**Comment by nicolas-raoul** [comment]
I just installed OSMTracker, recorded a track, uploaded it to OSM, and after a period in "PENDING", for some mysterious reason OSM suppressed my track, showing "Trace not found" at its URL.

Performing the procedure at https://github.com/labexp/osmtracker-android/issues/167#issuecomment-443377547 fixed the problem.

So, this is a urgent bug as it prevents people from using the tracks they record, which is the goal of the app.

**Comment by xsaco07** [comment]
Hello! I'm attending this possible issue. I'll test it and check weather the permissions are asked properly or not. Thanks for your help!

**Comment by xsaco07** [comment]
Hello, what version are you currently using?

**Comment by MattCost** [comment]
I am on 0.7.1
I don't recall what version I first installed when I had to manually assign the permissions

**Comment by xsaco07** [comment]
Oh! Ok, do you still have the same issue with that version?
