### ISSUE TITLE
Tags lost when stopping track

### ISSUE THREAD

**Issue by icrf2000** [labexp/osmtracker-android#170]
I noticed that when I stop the track (by tapping the disk icon in the top screen action bar), any tags I previously assigned to the track get overwritten by "osmtracker". Repro steps as far as I can tell:

- Start new track
- Assign tags to it, e.g. "holiday,usa,bike". Confirm them by tapping the SAVE button (disk icon)
- Stop the track
- Resume tracking
- Stop the track

Now long tap the track in the list, select "details" and you see the tracks "holiday,usa,bike" have been replaced by the default "osmtracker" again.

Not sure whether this is on purpose or a bug. I wouldn't know in which situation the behaviour would be useful, though.

**Comment by aton1698** [comment]
Hi, effectively that was a bug, and the PR #176 fix it.
Thanks for your contribution.
