### ISSUE TITLE
custom layout files are stored in folder for GPX export

### ISSUE THREAD

**Issue by zeliboba** [labexp/osmtracker-android#183]
Therefore when you change path for for GPX export, new track cannot be started since custom layout is not found. Please separate custom layout folder and folder for GPX export because it is misleading, and track cannot be started. Btw, I believe if layout location cannot be found (e.g. it is accidentally deleted), the track should be started with default layout instead of not starting.

**Comment by adam3497** [comment]
Hi @zeliboba 

Thank you for comment this problem, we will try to solve it in the coming days.

**Comment by adam3497** [comment]
This issue was closed with PR #199
