### ISSUE TITLE
Oauth tokens appear to point to wrong site: googlecode.com

### ISSUE THREAD

**Issue by SK53** [labexp/osmtracker-android#190]
I'm getting a 500 error when I try to upload a track. When I check my Oauth settings on the OSM website it cannot find the following url http://osmtracker-android.googlecode.com/.

I presume the two are related.

**Comment by aton1698** [comment]
Hi, what app version do you have installed?

**Comment by kavol** [comment]
I cannot upload tracks too, it might be the same problem ...

I have 0.7.1 installed from F-Droid.

After clicking 'Save and upload', I'm redirected to the browser. On the first try, it asked my OSM login, then it continued to a page asking for allowing the app to upload tracks. On subsequent tries,  it goes to this page directly.
Clicking to allow, I get

> Webpage not available
> The webpage at https://www.openstreetmap.org/oauth/authorize could not be loaded because:
> net::ERR_UNKNOWN_URL_SCHEME

trying to reload, the message changes to:

> Webpage not available
> The webpage at osmtracker://osm-upload/oauth-completed/?track_id=2&oauth_token=[hash]&oauth_verifier=[hash] could not be loaded because:
> net::ERR_UNKNOWN_URL_SCHEME

Now at https://www.openstreetmap.org/user/[username]/oauth_clients I see another "OSMTracker for Android™" line (it points to abovementioned http://osmtracker-android.googlecode.com/ ) but no track got uploaded.

Going to osmtracker settings, the 'Reset OSM authentication' option is still grayed out.

**Comment by xsaco07** [comment]
Hi, do you still have the same issue with the new current version? [0.7.2](https://f-droid.org/es/packages/net.osmtracker/)

**Comment by kavol** [comment]
> Hi, do you still have the same issue with the new current version? [0.7.2](https://f-droid.org/es/packages/net.osmtracker/)

yes, still the same with 0.7.2

**Comment by Binnette** [comment]
Probably fixed by #366 in [v2024.07.09](https://github.com/labexp/osmtracker-android/releases/tag/v2024.07.09)

Feel free to reopen this bug id needed.
