### ISSUE TITLE
Tiles loading extremely slowly

### ISSUE THREAD

**Issue by krubokrubo** [labexp/osmtracker-android#195]
Under "display track", the map tiles are loading excruciatingly slowly. I've waited over 1 hour to get zoom=14 tiles loaded in some areas.

It used to work fine 3 months ago, not sure what changed?

(I wonder if it's loading unnecessary tiles perhaps because it's used 50MB of data over 1 hour, but still doesn't load the tiles where I am. I also have the problem that it loses tiles often and they stay gray, not sure if it's related.)

EDIT: I see another user reporting the same problem as a review of this app in the Google Play store *today*. So I'm glad it's not just me. This makes me suspect a server issue? I already tried all 3 available tile providers in settings (started with MapQuest Open by default, also tried Mapnik and Cycle Map), but all have the same problem. Please let me know if any more information is needed to diagnose this?

EDIT2: Now I think this is a duplicate of #194 ...

**Comment by xsaco07** [comment]
Hello, we just solved the issue in the above PR.
You can take a look if you want, any observation is welcome.
Thanks for helping and reporting the issue!
