### ISSUE TITLE
v0.7 does not export Tracks

### ISSUE THREAD

**Issue by alexkemp9** [labexp/osmtracker-android#196]
## Phone:    
Model: VFD 600    
Android version: 6.0.1    
Kernel version: 3.10.49

## Issue:    
Have just created track1 within OSMTracker v0.7, my newly-installed update to v0.6.11. I have used the latter for ~4 years. Having exported a GPX it seems to have all Voice Recordings + Photo entries but zero tracks. That seems a bit of an existential problem.

In addition to having become a trackless tracker, photos are absent of almost all GPS info in the exif:

     ~/DCIM/Camera$ identify -verbose IMG_20190316_092818.jpg | fgrep GPS
    exif:GPSAltitudeRef: 240/100
    exif:GPSInfo: 686

In spite of the above, notice below that GPS is switched ON and present below for both voice recording + photos in the GPX, just not in the track.

This is what the top & bottom of the GPX export-file looks like viewed under less:-

     <?xml version="1.0" encoding="UTF-8" ?>
     <gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="OSMTracker for Android™ - https://github.com/labexp/osmtracker-android" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd ">
        <wpt lat="52.96083105" lon="-1.13161024">
                <ele>106.0</ele>
                <time>2019-03-16T08:12:18Z</time>
                <name><![CDATA[Voice recording]]></name>
                <cmt><![CDATA[compass: 220.21875
                        compass accuracy: 3]]></cmt>
                <link href="2019-03-16_08-12-18.3gpp">
                        <text>2019-03-16_08-12-18.3gpp</text>
                </link>
                <sat>0</sat>
        </wpt>
     …
        <wpt lat="52.95837756" lon="-1.130579">
                <ele>98.0</ele>
                <time>2019-03-16T09:29:16Z</time>
                <name><![CDATA[Voice recording]]></name>
                <cmt><![CDATA[compass: 334.65625
                        compass accuracy: 3]]></cmt>
                <link href="2019-03-16_09-29-17.3gpp">
                        <text>2019-03-16_09-29-17.3gpp</text>
                </link>
                <sat>0</sat>
        </wpt>
        <trk>
                <name><![CDATA[Tracked with OSMTracker for Android™]]></name>
                <trkseg>
                </trkseg>
        </trk>
</gpx>

#### 2019-03-23:    
Updated report with example GPS info within exif within photos.
#### 2019-03-19:    
Updated report with extract from the top of the GPX file + report on missing exif within photos.

**Comment by xsaco07** [comment]
Hi @alexkemp9 
First of all thanks for contributing.
I am trying to reproduce the fault you are describing using v0.7.1 but I haven't achieved that.

I export a track and the GPX has the correct tracks.
Here is a extract of what I get.

**Top**

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="OSMTracker for Android™ - https://github.com/labexp/osmtracker-android" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd ">
	<wpt lat="10.020013067527671" lon="-84.19683807553918">
		<ele>962.4600727921352</ele>
		<time>2019-03-12T22:08:22Z</time>
		<name><![CDATA[Extinguidor]]></name>
		<sat>0</sat>
	</wpt>
```
**Extract of the rest of the body**
```xml
<trk>
	<name><![CDATA[Trazado con OSMTracker para Android™]]></name>
	<trkseg>
		<trkpt lat="10.020156341198854" lon="-84.19672276633256">
			<ele>906.4028181638569</ele>
			<time>2019-03-12T22:04:50Z</time>
			<extensions>
				<speed>1.3496136665344238</speed>
			</extensions>
		</trkpt>
		<trkpt lat="10.0200065811777" lon="-84.19679639905348">
			<ele>912.862719733268</ele>
			<time>2019-03-12T22:04:51Z</time>
			<extensions>
				<speed>1.65536630153656</speed>
			</extensions>
		</trkpt>
		<trkpt lat="10.020091973274605" lon="-84.19679776787993">
			<ele>902.2660420872271</ele>
			<time>2019-03-12T22:04:52Z</time>
			<extensions>
				<speed>1.3118014335632324</speed>
			</extensions>
		</trkpt>
                ...
                ...
                ...
                ...
                ...
                <trkpt lat="10.019890094540152" lon="-84.196792072563">
				<ele>969.7865137858316</ele>
				<time>2019-03-12T22:15:58Z</time>
				<extensions>
					<speed>0.0</speed>
				</extensions>
	        </trkpt>
	</trkseg>
</trk>
```
In addition to that I uploaded that track to OSM successfully.

![Traza](https://user-images.githubusercontent.com/29348322/55917433-89729080-5bac-11e9-964d-4e8fd5f0b848.png)

We'll be aware of this since now but by the moment we are not able to reproduce it.

**Comment by jamescr** [comment]
I haven't been able to reproduce the not tracking issue neither. Don't know how to help.

**Comment by EmmanuelAB** [comment]
As we couldn't find a way to reproduce this bug, this issue will be closed.
