### ISSUE TITLE
v0.6.11 does not save all Photo- nor Sound-files

### ISSUE THREAD

**Issue by alexkemp9** [labexp/osmtracker-android#198]
## Phone:    
Model: VFD 600    
Android version: 6.0.1    
Kernel version: 3.10.49

## Issue:    
Having discovered that [OSMTracker v0.7 does not track](https://github.com/labexp/osmtracker-android/issues/196) I reverted to v0.6.11 (previously used since 21 March, 2016) and made another track on March 21. v0.6 DOES produce a viable GPX and also has full GPS info within the exif for both photos and sound-files. However, 42% of all the photographs shot were not saved by OSMTracker and therefore do not feature within the GPX export. A similar situation occurs with 3GPP (sound) files, but I cannot quantify the numbers.

1. OSMTracker default photo source = 'Camera'.
2. When taking a photo during tracking, the utility used appears to be supplied by OSMTracker, and files are saved into:

          osmtracker/data/files/track1

3. Nevertheless, I have always found that duplicate photos are also saved into the default location used by the Smartphone; currently that is:

          DCIM/Camera/

4. When 'Stop & Save' is chosen + a GPX file is exported, those files appear within:

          osmtracker/2019-03-21_10-34-15

5. All directories were copied from Smartphone to a Desktop computer and the number of photos compared. Those within the two osmtracker/ directories were identical, and also duplicated within the DCIM/ directory. However, there were considerably more within DCIM than osmtracker:

          osmtracker: 107
          DCIM:       183 (+76 / 42% extra)

## Coda    
I have always suspected that something, somewhere was wrong with OSMTracker without ever being able to put my finger on what it was. Then I discovered that v0.7 did not track, so I thought to check all checkable-aspects of v0.6. Sure enough, I found that it cannot save all photo- or sound-files.

Does anyone do any bug-checking on these programs?

**Comment by EmmanuelAB** [comment]
I've tried to reproduce this. Here's what I found:

- In deed on *some* tracks it didn't save all the photos I took. However on others it saved all of them.
- The number of missing photos is arbitrary: some cases lost 0, 1, 2, 5, 3, 9 etc. Even when I took different amounts of shots in each track.
- The amount of photos at `osmtracker/data/files/` and the ones at the folder created after exporting the track are the same. They're not lost in the movement of files. 
- I put a log message when recording the tracks, that appears each time a photo is saved to storage after returning from the camera back to the tracker. And it shows the same number of logs that the number of photos taken.
- It looks like the photos are not even saved to `osmtracker/data/files/`in the first place. Therefore they're not moved to the folder when exporting a track.

**Conclusion:**  After this testing I wasn't able to find something wrong with the tracker. That led me to think that for further effort to fix this, it'd be good idea giving a look at the photo-taking service used by the app. I wrote what I found if it's useful for someone else trying to fix this problem.

**Comment by alexkemp9** [comment]
> The number of missing photos is arbitrary

That is also the case with myself. It is possible that my report here is at the high end of losses, but some always seem to be lost.

My suspicion is that if I take lots of photos then I also seem to be more likely to lose some of them. However, I've lost the will to quantify this.

The fact that the numbers are arbitrary strongly suggests a programmatic error, rather than a hardware error, though good luck in finding it.
