### ISSUE TITLE
First track records no trackpoints, at new install or after clear data/permissions (android 9)

### ISSUE THREAD

**Issue by jdmonin** [labexp/osmtracker-android#207]
After installing the app, the first track doesn't record any waypoints: After clicking `+` to start the new track, android 9 asks you to grant the location permission. Do so, and it looks like it's recording. Waypoints work fine and have correct GPS coordinates. But 0 trackpoints are recorded.

The next track's trackpoints are OK, because it already has the runtime permission when that track started recording.

![Permission popup during recording](http://jdmonin.nand.net/img-embed/osm_Screenshot_20190602-gps-perm.png)

![Track list: First has 0 waypoints](http://jdmonin.nand.net/img-embed/osm_Screenshot_20190602-tracklist.png)

This bug hit me on an Android 9 phone, but might apply to 6 and above (when the runtime permissions system was introduced).

To reproduce, go to Android Settings -> Apps -> OSMTracker and do any of:
- Permissions -> Location -> Remove
- Force Stop, then Storage -> Clear storage  [and permissions]
- Uninstall, then reinstall

I can reproduce this on the most recent Google Play release (0.7.1); master (1380a22); develop (fa1dce41).

**Comment by aton1698** [comment]
Fixed with PR #213
