### ISSUE TITLE
[OpenStreetMap] GPX Import failure

### ISSUE THREAD

**Issue by 2Belette** [labexp/osmtracker-android#222]
Trying to `Upload to OpenStreetMap`, no error from UI/UX (Pop-up windows says that the upload is OK).

But I am receiving an email from OpenStreetMap : 

> GPX Import failure
>  It looks like your GPX file osm_upload897046553.gpx with the description test and the following tags: osmtracker osmtracker failed to import. Here is the error:
> 0 points parsed ok. Do they all have lat,lng,alt,timestamp?

Doing a `Export to GPX` and importing manually to OpenStreetMap is working fine :

> It looks like your GPX file Sep_15__2019_20_31_27_2019_09_15_20_31_27.gpx with the description test and no tags. loaded successfully with 119 out of a possible 119 points.

Any reason why the included function from OSMTracker is not working on my side ?

I have double checked and latitude/longitude & timestamp are in the GPX file !

Is it a known issue ?

Thanks

Version from F-Droid : v0.7.1

**Comment by xsaco07** [comment]
Hi @2Belette, thank you for your cooperation!

Indeed it is a known issue. Actually it's related to the app storage permissions. It was solved for the new version 0.7.2, which can be downloaded from the App Store (very soon will be available on F-Droid).

Here is the [Fix explanation](https://github.com/labexp/osmtracker-android/pull/205).

Regards!

**Comment by xsaco07** [comment]
Hi! The version is already available on F-Droid! 
You can check it [here](https://f-droid.org/es/packages/net.osmtracker/).
The issue shouldn't happen again using that version.

Regards!
