### ISSUE TITLE
Feature Request : A forever option for setting time

### ISSUE THREAD

**Issue by theryecatcher** [labexp/osmtracker-android#223]
When we choose to share location can we have a forever option of sharing the location with the intervals being in hours. Just this could be helpful if we don't want to keep on explicitly sharing the locations every time or if we forget to do so. Can be useful when you're using teh location sharing feature for safety purposes of children/SO.

Thanks.

**Comment by Binnette** [comment]
I close as I don't understand this issue. Feel free to reopen if needed.

The issue talk about "sharing location", but OSMTracker is not a app to share his location. Please clarify.
