### ISSUE TITLE
Infinite loop / UI freeze when location permission was denied with "never ask again" checked

### ISSUE THREAD

**Issue by farmazon3000** [labexp/osmtracker-android#249]
1. Start app, start logging trace
2. App asks for location permission
3. On the dialog for granting permission to location check "never ask again" and choose "deny".

App gets in infinite loop + UI freeze because it's constantly. [The Toast](https://github.com/labexp/osmtracker-android/blob/master/app/src/main/java/net/osmtracker/activity/TrackLogger.java#L346) at the bottom "pulses" because it's constantly being shown again and again.

[Reason of it is here](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/90).

**Comment by farmazon3000** [comment]
Same issue on google samples:
https://github.com/android/location-samples/issues/83

**Comment by Wolam** [comment]
I've reinstalled the app and after step 3 I don't get any loop. Do you refer the loop as not being able to log traces? On my device when location permissions are denied the traces are created however the stop immediately, maybe this is the loop you refer to because I can do this how many times I want.

**Comment by Romamok** [comment]
"never ask again"

Did you check that? This is crucial.

**Comment by Wolam** [comment]
@farmazon3000 Unfortunately we couldn't replicate the loop with the given instructions, would be helpful if you could add some additional info (screenshots or logs) related to the issue.
Also @Romamok it seems the error is related to Android locations API, if there is any solution given by them we will try to incorporate it asap.
