### ISSUE TITLE
Can't upload 

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#258]
Now every time I try to upload, it just says export successfully and then the app crashes. But I didn't intend to export, I intended to upload.

**Comment by jidanni** [comment]
Yes, I even reauthorized the app to make sure that wasn't the problem.

**Comment by jamescr** [comment]
What osmtracker version?

**Comment by jidanni** [comment]
0.7.2-beta3

**Comment by jamescr** [comment]
I tested that version and can't reproduce the problem. But on v1.0.0 I found a bug when trying to upload a GPX to OSM. If you want to detail more on the bad function I could try to reproduce it again.

**Comment by jidanni** [comment]
(Indeed, you are correct about the version. It turns out the Google Play, even though it says I'm a beta tester, shows me the wrong version. That day I was copying the version from Google Play plus my cell phone was at  Grandma's house.)

**Comment by jamescr** [comment]
Thanks for the bug report @jidanni . We are going to upload a new beta version with the bux fixed.
