### ISSUE TITLE
User preference storage_dir ignored for fotos

### ISSUE THREAD

**Issue by icrf2000** [labexp/osmtracker-android#267]
Fotos go to a fixed directory, regardless of what the user sets as preference prefs_storage_dir.

app/src/main/java/net/osmtracker/db/DataHelper.java:
```
	public static File getTrackDirectory(long trackId) {
		File _return = null;
		
		String trackStorageDirectory = Environment.getExternalStorageDirectory()  
		+ "/osmtracker/data/files/track" + trackId;
```
(Really nothing severe... I stumbled over it by chance when testing other stuff.)

**Comment by Binnette** [comment]
Fixed in #451 #458
