### ISSUE TITLE
Problems exporting GPX file

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android#271]
Though the app creates one, and if I open it in text editor like Notepad I see what looks suitable data, QGIS refuses to read it as correct data so cannot display it.  Also this happens with the app Locus.
Can you propose a solution so I can map the tracks from OSMTracker in QGIS ?

* Issue reported by Keith Cohen vía email.

**Comment by mnalis** [comment]
Importing `.gpx` created with `OSMTracker 1.0.1` into `QGIS 3.10.14+dfsg-1~bpo10+1` seems to work just fine for me.
Do we have any more details on exact problem (example gpx file that fails, software versions, screenshots, ...) ?

**Comment by jamescr** [comment]
No new updates from Keith Cohen. I'll close the issue since we can't reproduce the error and @mnalis  confirms it's working ok.
