### ISSUE TITLE
Trackpoints are dated 20 years in the past with Mock Location

### ISSUE THREAD

**Issue by PontiacCZ** [labexp/osmtracker-android#283]
I use external GPS receiver connected via bluetooth to obtain the most accurate position. I carry the GPSr on the top of my hat to have the best view at the satellites and avoid my body's shadow. :-) The receiver is connected with the phone via the "Bluetooth GPS" application and injects obtained coordinates into the system using technology called Mock Location in Android 9 developer options.

It has worked very well for a couple of years. Until about three weeks ago. Something has happened, I suspect an update in Android 9 on my CAT S61. OSMTracker started to write trackpoints and waypoints with wrong date. Time is right. Just the date is off by 7168 days in the past.

E.g. in my tracklog from yesterday (2020-09-22) all trackpoints are dated in 2001-02-06. A few days back, in Sep 15, 2020, I captured a log with 2001-01-30 timestamps.

The same thing is happening on my backup phone with Android 10 (Xiaomi Mi A3). Again that difference of 7168 days.

---

This is part of my captured GPX file. Notice that the voice record filenames are created with correct date which means OSMTracker knows it.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="OSMTracker for Android™ - https://github.com/labexp/osmtracker-android" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd ">
	<wpt lat="49.016911" lon="17.585543">
		<ele>265.3</ele>
		<time>2001-02-06T14:25:01Z</time>
		<name><![CDATA[Voice recording]]></name>
		<link href="2020-09-22_16-25-01.3gpp">
			<text>2020-09-22_16-25-01.3gpp</text>
		</link>
		<sat>0</sat>
	</wpt>
	<wpt lat="49.017209" lon="17.586573">
		<ele>269.1</ele>
		<time>2001-02-06T14:26:30Z</time>
		<name><![CDATA[Voice recording]]></name>
		<link href="2020-09-22_16-26-30.3gpp">
			<text>2020-09-22_16-26-30.3gpp</text>
		</link>
		<sat>0</sat>
	</wpt>
	<wpt lat="49.017253" lon="17.586845">
		<ele>269.6</ele>
		<time>2001-02-06T14:30:10Z</time>
		<name><![CDATA[Voice recording]]></name>
		<link href="2020-09-22_16-30-10.3gpp">
			<text>2020-09-22_16-30-10.3gpp</text>
		</link>
		<sat>0</sat>
	</wpt>

    .
    .
    .

	<trk>
		<name><![CDATA[Tracked with OSMTracker for Android™]]></name>
		<trkseg>
			<trkpt lat="49.017464" lon="17.584666">
				<ele>263.6</ele>
				<time>2001-02-06T14:18:23Z</time>
				<extensions>
					<speed>0.005144444294273853</speed>
				</extensions>
			</trkpt>
			<trkpt lat="49.017473" lon="17.584671">
				<ele>264.7</ele>
				<time>2001-02-06T14:22:16Z</time>
				<extensions>
					<speed>0.06687777489423752</speed>
				</extensions>
			</trkpt>
			<trkpt lat="49.017463" lon="17.584664">
				<ele>265.0</ele>
				<time>2001-02-06T14:22:48Z</time>
				<extensions>
					<speed>0.0720222219824791</speed>
				</extensions>
			</trkpt>
			<trkpt lat="49.017473" lon="17.58466">
				<ele>266.1</ele>
				<time>2001-02-06T14:22:51Z</time>
				<extensions>
					<speed>0.3961222171783447</speed>
				</extensions>
			</trkpt>

    .
    .
    .

		</trkseg>
	</trk>
</gpx>


```

This ONLY happens when using external GPSr via mock location technology. With internal GPS chip, the trackpoints have correct date.

## Steps to reproduce:

On Android 9 or 10:

1) Connect a bluetooth GPS receiver via "Bluetooth GPS" application, allow for mock location and wait for a fix.
2) Launch OSMTracker and capture a short tracklog.
3) Export a GPX and inspect the trackpoints' date.

**Comment by Eiim** [comment]
Probably related to https://en.wikipedia.org/wiki/GPS_Week_Number_Rollover, where GPS dates reset every 19.7 years.

**Comment by PontiacCZ** [comment]
You were right. I should have noticed that the date was already wrong on the Bluetooth GPS dashboard. Just one thing puzzles me:  which rollover happened three weeks ago when second rollover was on April 6, 2019 and the third one will happen in November 2038? :-)

Never mind. I downloaded Qstarz FW and that fixed it. Thank you!
