### ISSUE TITLE
Cause of the jump in the route record

### ISSUE THREAD

**Issue by ya30in** [labexp/osmtracker-android#294]
![Screenshot_2021-01-17-13-35-22-180_net osmtracker](https://user-images.githubusercontent.com/44711326/105665535-887b3200-5eec-11eb-9260-eb8b25de2368.jpg)

**Comment by jamescr** [comment]
That jump happens when the device loss GPS signal, the starting point of the jump was the previous GPS point before losing signal and the end of the jump is the point where the signal was recovered.
