### ISSUE TITLE
Some tracks can't be uploaded or exported

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#296]
![Screenshot_20210126-131536.jpg](https://user-images.githubusercontent.com/1230959/105803811-306e2980-5fd9-11eb-95a0-dd77c5acc60a.jpg)

Other tracks take several attempts can finally work. This all started happening with your new version.

**Comment by jidanni** [comment]
It says V1 0 0 beta 3 but I can't copy it from the screen because you won't let me.

**Comment by jidanni** [comment]
Yes today I sent a feedback like the picture asks me. See if you can find it. Thanks.

**Comment by jidanni** [comment]
So it always crashes for that track number 70 in the preparing export phase.

**Comment by jidanni** [comment]
The only thing special about that track is after I pushed the save button I went to the notifications and pressed the notification and it seemed like it was resuming tracking.

Okay I guess I'll have to hook my cell phone to the computer and going to ADB and get the database out of your app.

**Comment by jidanni** [comment]
So there's probably some poison characters inside some text note that I made.

**Comment by jidanni** [comment]
Yes, short tracks have no problems being exported or uploaded.

**Comment by jamescr** [comment]
Thanks. I found issues exporting and/or uploading to osm tracks without waypoints or trackpoints. I fixed in this PR #292.

**Comment by jidanni** [comment]
OK, I finally (after giving the phone a rest (or at least restarting the app) uploaded https://www.openstreetmap.org/user/jidanni/traces/3563418 and also (restarted app first again)
exported it to GPX. Yes it does have waypoints.

**Comment by jidanni** [comment]
Before finally succeeding here's what I found in
```
  /sdcard/osmtracker:
$ ls -og
-rw-rw---- 1 169272 01-26 13:15 2021-01-26_11-03-51_2021-01-26_11-03-55.gpx
-rw-rw---- 1 204738 01-26 13:16 2021-01-26_11-03-51_2021-01-26_11-03-551.gpx
-rw-rw---- 1 179489 01-26 13:40 2021-01-26_11-03-51_2021-01-26_11-03-552.gpx
-rw-rw---- 1 178138 01-26 13:41 2021-01-26_11-03-51_2021-01-26_11-03-553.gpx
-rw-rw---- 1 178543 01-26 13:42 2021-01-26_11-03-51_2021-01-26_11-03-554.gpx
$ tail *|grep time|sed 's/\t\+//'
<time>2021-01-26T04:37:08Z</time>
<time>2021-01-26T04:48:46Z</time>
<time>2021-01-26T04:41:24Z</time>
<time>2021-01-26T04:41:17Z</time>
<time>2021-01-26T04:41:18Z</time>
$ wc -l *
  6261 2021-01-26_11-03-51_2021-01-26_11-03-55.gpx
  7570 2021-01-26_11-03-51_2021-01-26_11-03-551.gpx
  6639 2021-01-26_11-03-51_2021-01-26_11-03-552.gpx
  6590 2021-01-26_11-03-51_2021-01-26_11-03-553.gpx
  6603 2021-01-26_11-03-51_2021-01-26_11-03-554.gpx
 33663 total
$ wc -l *|colrm 2-
colrm: first argument: '2-'
$ for i in *; do wc -l < $i; done
6261
7570
6639
6590
6603
```

**Comment by jidanni** [comment]
I got a wild idea. Maybe osmtracker should say:
Hmmm, I perhaps will need xxxxxxx bytes of memory for the next operation.
Hey Android, give me xxxxxxx X 2 memory please. Some disk too.
OK, now proceed with the operation.
That would be better than running out "in the middle of the dinner party."
But odd, my phone has plenty of disk and memory. So maybe it is some other problem.
Anyway, I did sent the "Feedback" mentioned above. Perhaps you got it.
