### ISSUE TITLE
Always <sat>0</sat>, despite screen

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#298]
```
$ cd /sdcard/osmtracker
$ grep -h '<sat>' *.gpx | sort | uniq -c
    623                 <sat>0</sat>
```
But I recall while using the app, it mentioned I had 9 out of 16 satellites or something.
Anyway, if it is too much trouble to fix, might as well leave it out of the GPX.

**Comment by jamescr** [comment]
This is related with the `TrackLogger` activity and not with the export, the export is checked in `ExportTrackTest` unit test.
