### ISSUE TITLE
App not tracking when goes on background (Android 11, v1.0.0-beta)

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android#299]
The app is not requesting for location access all time, so when the user move OSMTracker to background it just stops tracking. 

The bug was reported and verified for Android 11 devices. (Could be affecting devices with android 10+)

This bug was reported by Mark Begbie (Thanks!)

**Comment by openstrike** [comment]
This still appears to be happening, unfortunately. I was using v. 1.0.1 today and it did not track while the display was off. This is on Android 11 on a Samsung Galaxy A41.
