### ISSUE TITLE
Export does not work due to EPERM (Operation not permitted)

### ISSUE THREAD

**Issue by Strubbl** [labexp/osmtracker-android#306]
Hi,
since the latest release or Android upgrade i cannot export my routes anymore. It says that it cannot open the gpx file in storage due to EPERM (Operation not permitted).
The export worked back on 2021-02-27. 
I am using stock Android 11 on a Motorola Moto g pro

Okay, if i look into the file system the export somehow worked kinda... I have the folder and the files. But i have a lot of temporary folders and files.

This is the screenshot with the error message:

![grafik](https://user-images.githubusercontent.com/97055/110220967-8d5ada80-7ec9-11eb-9b61-e83ac3623d87.png)

**Comment by tsingi** [comment]
My German is limited to counting and swearing but it looks like the app does not have the necessary permissions to write to a file. One would think it would ask you about that.
I looked in settings/apps/osmand/permissions and I see four switches.
Camera
Location
Microphone
Storage
If you go there, is storage on? It isn't for me but I haven't tried to write any data.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Strubbl** [comment]
Yes, storage is on. It worked like one week ago. 

i changed system language to english and made new screenshots. I updated the first post in this thread. and here's my permissions:

![grafik](https://user-images.githubusercontent.com/97055/110220972-951a7f00-7ec9-11eb-8466-e072147e3560.png)

**Comment by Strubbl** [comment]
Ok, i found out that this issue appeared since the last update to version 1.0.0. My last android system update was on 2021-02-12 and after that OSMTracker did still work.

**Comment by jamescr** [comment]
> Okay, if i look into the file system the export somehow worked kinda... I have the folder and the files. But i have a lot of temporary folders and files.

Can you take a screenshot of the temporary folder? Curious about what temp files are there.

**Comment by jjiglesiasg** [comment]
2021-05-03: When you try to upload a track to OSM, says host could not be resolved www.Openstreetmap.org

**Comment by Strubbl** [comment]
> > Okay, if i look into the file system the export somehow worked kinda... I have the folder and the files. But i have a lot of temporary folders and files.
> 
> Can you take a screenshot of the temporary folder? Curious about what temp files are there.

Sorry, i cannot reproduce this anymore.

**Comment by jamescr** [comment]
this issue is fixed in v2024.07.09.
