### ISSUE TITLE
Exporting to GPX duplicates the timestamp in the filename

### ISSUE THREAD

**Issue by gbuendia** [labexp/osmtracker-android#308]
**Previous behaviour:**

File was exported as `2021-03-01_14-11-32.gpx`

**Current behaviour**

File is exported as `2021-03-19_14-33-31_2021-03-19_14-33-31.gpx`

**Comment by jamescr** [comment]
I need some more info:

* What name the trace had?

* What option have you selected for the Name of the file for the traces? (You check it in Configuration)

**Comment by gbuendia** [comment]
Oh. I think you hit the nail there.

I never name the tracks, I just hit (+) and leave the automatic name (which is the date and time).

The option in settings is name + date/time.

Guess before I had one of the other two options (just name or just time), but today when I opened the app I got the "first time tutorial" so guess I somehow reset something?

**Comment by jamescr** [comment]
Actually, was a bug with the export, prior 1.0.0 the app was not
considering the selected setting. That was fixed and now is working as
should be.

The first time tutorial don't reset any setting.

**Comment by gbuendia** [comment]
Looks like a non issue. I'm not very familiar with the issues etiquette but I guess it's OK for me to close it, as there is no action to be taken?
