### ISSUE TITLE
UI buttons for marking waypoint features remain disabled even after acquiring an accurate position fix

### ISSUE THREAD

**Issue by Lee-Carre** [labexp/osmtracker-android#315]
OSMtracker v1.0.1 on Android v10 on SM-A405FN

I think my usage scenario might be a relevant factor, so I'll describe it for context.

When I'm prompted to record a new GNSS trace for OSM, I'm already out & about surveying (hence noticing that a real-world way is missing from OSM, and wanting to capture it so that it may be added (later)). This means that I already have a bunch of apps running which are making use of GNSS; thus it's already actively receiving & processing signals to yield position fixes. For several reasons, I can't simply stop those apps for the sake of OSMtracker work-arounds (nor should I have to, anyway).

When launching OSMtracker and instructing it to record a trace, the UI text initially indicates that it's awaiting an accurate fix before logging points to the (GPX) trace.

This seems to indicate that its design assumes a ‘cold start’ with respect to the GNSS subsystem having accurate position fixes. Which isn't use case in my usage.

While OSMtracker does record track-points, it won't let me mark notable features with the UI buttons (and reports that they're disabled until an accurate fix is obtained, even though it already has such a fix and is logging points).

Once, when I paused a trace (or simply back-buttoned to the main menu), and immediately resumed the same trace, the UI let me use the buttons to note features.
I have not been able to achieve this, again, with subsequent traces. That was with an earlier version, though.

However, the misdetection of already having accurate position fixes is consistent for each new trace.

Having tried telling OSMtracker to start a trace when the GNSS subsystem **wasn't** already active (i.e. not out doing surveying), the behaviour of OSMtracker is what one would expect.

The thing is, having had plenty of experience with using GNSS receivers over the years, as a matter of good practice I would always have another (background) app activate the GNSS subsystem in order that it can achieve stability (especially position accuracy) before starting any type of logging of the fixes it outputs. All in order to produce clean logged data from the outset without any anomalous points which need to be ignored or removed.

May I suggest having OSMtracker check/test the position accuracy, in order to decide when to activate the UI buttons, instead of assuming a ‘cold start’ and soft-failing when it experiences a ‘hot start’. This would seem to yield the best results for the most use-cases.

**Comment by Binnette** [comment]
I close as "fixed" by #457. Test again the bug when the develop version will be published. If the bug still happens please reopen this issue.
