### ISSUE TITLE
layouts are not updating although the pull request has been merged

### ISSUE THREAD

**Issue by Nick-Tallguy** [labexp/osmtracker-android#325]
On 29th March my pull request for Detailed Tracks update to version 2 was merged. However on the app, only the older version is still available.  
Also , I have created a branch 'canal' and have been working on a new layout - on the app I have added my repo. and the 'canal branch' - the app reports that the repository exists, but does not update the list of available layouts.  
  
Android Version 11 on Google pixel 3a.  
OSMTracker (Beta) v1.0.1  
  
Regards & thanks for reading  
Nick

**Comment by Binnette** [comment]
I guess it is fix now. If not feel free to reopen. If so, add link to your PR and the name of your layout.
