### ISSUE TITLE
Cannot superimpose track on local map? Feature request.

### ISSUE THREAD

**Issue by afc54** [labexp/osmtracker-android#334]
I have just installed OsmAnd~ 4.1.11 and OSMTracker for Android 1.0.1. Very happy to have found a non-google solution.  Made a track but I can't see it superimposed on the map installed on my phone.  Of course I saw the option to upload it to OpenStreetMap (requires an internet connection) but the whole reason for installing OSMAnd~ and OSMTracker was so that my tracks remain on my phone and private.  It seems natural that, if OSMAnd~ is installed locally and there is a local map, the created tracks would be superimposed on that, with no need to go to "the cloud" (a misnomer in my opinion, just other people's computers).  Sharing to the cloud should remain optional, not mandatory in order to see the track superimposed on the map.

I have noticed that the track is not zoomable.  This subject is discussed here: https://github.com/labexp/osmtracker-android/issues/95 and it appears a background map is necessary for the zoom option to work. What could be more natural than the map that's already installed locally?

Is it possible to have OSMTracker find out if there is a local map installed and use that by default? The track itself on a black background, not zoomable, is not that interesting or usable.  Failing that, a button/option to "side load" it (or whatever term would be appropriate here) to the local map would be extremely useful.

Is there an existing way to do this?  I notice there is a plugin in OSMAnd~ to do trip recording.  Is this independent of OSMTracker, does it work with OSMTracker? does it depend on it? I've tried it briefly but I like the richness of features in OSMTracker

**Comment by icrf2000** [comment]
Hello,

OsmTracker and OsmAnd are unrelated, there is no interaction or dependency between them.

You say "...The track itself on a black background, not zoomable, is not that interesting or usable...", but...:

OsmTracker can show a background map. The map data are OpenStreetmap and are retrieved and rendered using the OsmDroid library. Data of an area that you already watched are cached and available offline. Of course the map is zoomable.

Here an example  of how it looks and a screenshot of the settings dialog where you can enable it. Unfortunately I only have screenshots in German right now, but they should give you a hint where to find it.


![osmtracker_map](https://user-images.githubusercontent.com/11777822/179342135-c723f04e-e57c-4265-8957-9295f4846cd1.jpg)
![OsmTracker_settings_01](https://user-images.githubusercontent.com/11777822/179342146-23323259-a053-4592-a9c5-2ed983086ed5.PNG)

**Comment by iDawer** [comment]
OSMTracker can export GPX tracks that can be imported into OsmAnd.

1. In OSMTracker tap `Export as GPX` in context menu of a track to export;
2. In OsmAnd go to: Main menu -> `My Places` -> `Tracks` tab -> `+` button in lower bar. It should ask for a program to use to select a file from the filesystem. Use your preferred one for filesystem exploring (I'm using Total Commander);
3. In filesystem exploring program locate the GPX file that has been exported in step 1. (In my case it is `/storage/sdcard0/osmtracker/YYYY-MM-DD_HH-MM-SS/TRACK-NAME_DATE-TIME.gpx`). Select it;
4. Done! The track didn't leave your phone.

Or you can use OsmAnd as GPX viewer tool without importing them. Just skip the 2nd step and open the exported track in your filesystem explorer program. In my case Total Commander opens GPX files with OsmAnd by default.

_Actual for Android 4.2.2, OSMTracker 0.7.1, OsmAnd 3.3.8_ 



> I have just installed OsmAnd~ 4.1.11 and OSMTracker for **Android 1.0.1**.

I suppose it's a typo. 1st Android came out back in 2008. It is hard to find such phones these days.

**Comment by Binnette** [comment]
I close the issue as 2 android apps can not share "easily" their private data. Also see suggestions above. Example: once you finished recording your track then export the track from OSMTracket and open it in OsmAnd. Concider also using OsmAnd to record track and use "quick action buttons" of OsmAnd in replacement of OSMTracker.
