### ISSUE TITLE
Increase targetSdkVersion to 30+

### ISSUE THREAD

**Issue by grrrrr** [labexp/osmtracker-android#342]
Starting 1st November 2022,  any app that does not have a `targetSdkVersion` of at least `30` will  not be discoverable or install-able from  Google Play Store on new devices.

https://support.google.com/googleplay/android-developer/answer/11926878

The current `targetSdkVersion` of OSMTracker is [29](https://github.com/labexp/osmtracker-android/blob/245dafdb3291879aa7fb17ecf919108bb49d828e/app/build.gradle#L14)

It would be useful to get a maintenance release (if anyone is still able to) to at least allow continued installation on new devices.  Outside of that the app works fine on Android 13.

**Comment by jamescr** [comment]
We received a deadline extension to comply with these changes, to May 1, 2023

**Comment by jamescr** [comment]
Version 2024.07.09 solved this issue.
