### ISSUE TITLE
Switch to OAuth 2

### ISSUE THREAD

**Issue by danieldegroot2** [labexp/osmtracker-android#359]
Switch to OAuth 2 from HTTP Basic Auth and OAuth 1.0a. They are being deprecated.
See https://github.com/openstreetmap/operations/issues/867

**Comment by mnalis** [comment]
Note critical days: https://github.com/openstreetmap/operations/issues/867#issuecomment-191195405

> Repeating [the announcement](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490),
> The Operations Working Group is shutting down OAuth 1.0a and HTTP Basic Auth in 2024. They have been deprecated since 2023 and their role in authorization has replaced by OAuth 2.0 which the standard authorization method for most systems. This change will have three key dates:
>  -  March 1st, 2024: New OAuth 1.0a application registrations are disabled. Existing applications will not be impacted. HTTP Basic Auth will not be impacted.
>  -  May 1st, 2024: Sysadmins will start brownouts to find applications that are still using OAuth 1.0a or HTTP Basic Auth
>  -  June 1st, 2024: OAuth 1.0a and HTTP Basic Auth will be shut down.

- That is assuming this project is still alive :cry:  - see e.g. https://github.com/labexp/osmtracker-android/issues/356

**Comment by mnalis** [comment]
Any news on OAuth2 support?

Login will [stop working in few days](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490/16), on 1 Jun 2024, unless this is fixed and OAuth2 is implemented.

**Comment by jamescr** [comment]
I have a PR draft (locally) that upgrades OSMTracker to support OAuth2, is based on [AppAuth-Android](https://github.com/openid/AppAuth-Android) and a [recent contribution]( https://github.com/westnordost/osmapi/issues/36) to [osmapi](https://github.com/westnordost/osmapi). I estimate that I will be able to upgrade OSMTracker by next weekend (in the next days I'll upload the PR draft).
