### ISSUE TITLE
OSMTracker v2024.07.09: Question marks in 'Accuracy ..m (?/?)' line

### ISSUE THREAD

**Issue by jer194** [labexp/osmtracker-android#442]
Hello,

the most recent version of OSMTracker (in Fdroid) shows question marks in the 'Accuracy' line,
instead of the number of satellites. Is it a minor bug?
It was working correctly in the previous version.
![t2](https://github.com/user-attachments/assets/ff54602d-65e7-4706-8e4c-51bf79256611)

Thanks - Jakob.

**Comment by jamescr** [comment]
This is a minor bug. The number of satellites was obtained from the [GpsStatus, now deprecated for the API level we are using](https://developer.android.com/reference/android/location/GpsStatus).I didn't found an easy way to get the number of satellites without the deprecated API so I put the question marks in the satellite numbers. Also I didn´t invest a lot of time considering that the priority of version 2024.07.09 was [implement oauth2](#359)   and  have the app listed again in PlayStore.

**Comment by Binnette** [comment]
Fixed by @Zahnstocher  in #442
