### ISSUE TITLE
Notifications blocked

### ISSUE THREAD

**Issue by nzbegbie** [labexp/osmtracker-android#453]
I am unable to turn notification on. In the app settings the option is greyed out with the message that all notifications are blocked. In the notifications setting for Android, OSMtracker is not listed either as a user or system app.

I'm on the 9th July 2024 update, on a Samsung Galaxy S22 Ultra, Android 14

![Screenshot_20240827_124945_Settings](https://github.com/user-attachments/assets/eac40580-901e-4b2d-ac1b-b30a2cccfb17)

![Screenshot_20240827_125224_Settings](https://github.com/user-attachments/assets/b5677ef3-72f0-40f8-867c-652b0c981354)

![Screenshot_20240827_125409_Settings](https://github.com/user-attachments/assets/752254a2-c18f-430a-9602-7d64c8c682e0)

**Comment by Binnette** [comment]
Fixed by @Andyporras in PR #454
