### ISSUE TITLE
Missing waypoints

### ISSUE THREAD

**Issue by FR3DD221** [labexp/osmtracker-android#464]
When a track is being recorded we can put some waypoints to show some important points of the location, some of these waypoints could be photos, voice notes or text notes. but this three are presenting a problem, except for the photo the rest doesn't appear on the list of waypoints, a when the track is finished, the also does not appear, but, when we export the track, with the button “export as gpx”, and we go to the phone files, we can see the photo and the voice note, but the text note doesn't appear here either.
This is happening in the version located in “develop” branch, not in the version of Play Store.

**Comment by Binnette** [comment]
So to sum up your message:

| Waypoint Type | Shows in Waypoint List | Exports as GPX |
|---------------|------------------------|----------------|
| Photos | ✔️ | ✔️ |
| Voice Notes | ❌ | ✔️ |
| Text Notes | ❌ | ❌ |

Is that correct @FR3DD221

**Comment by Binnette** [comment]
Hi @FR3DD221, I fixed the issue on develop branch. Can you please test again?

**Comment by miltonials** [comment]
Hi, I just tested the changes and they work fine.

| Waypoint Type| Shows in Waypoint List| Exports as GPX|
|--------|--------|--------|
| Photos | ✔️| ✔️ |
| Voice Notes| ✔️ | ✔️ |
| Text Notes| ✔️ | ✔️ |

**Observation**: text notes allow an empty description. I believe this is not necessary for a trace.

**Comment by Andyporras** [comment]
Hi @Binnette,

I was testing the changes on Wednesday, and I can confirm that they work perfectly, as mentioned by @miltonials.

**Comment by Binnette** [comment]
Fixed in 1f749166157b5bfc49e1b728b2731d8546b63211
