### ISSUE TITLE
'Display track': no background map anymore

### ISSUE THREAD

**Issue by jer194** [labexp/osmtracker-android#467]
Since a few days (or weeks?) the 'Background map' is not shown anymore (enabled in settings, also Internet access is allowed).
I have tried while using the stable version, and also the Nightlies.
Maybe this is due to changes in the API to OSM (simiar: https://github.com/labexp/osmtracker-android/issues/360 / OpenStreetMapConstants.java)?

Thanks - Jakob.

**Comment by Binnette** [comment]
Hi @jer194, TY for submitting an issue. Can you give us more details about your phone:

- Phone branch and model
- Android version of your phone

Can you also try to upload a track on OSM via the app? I want to check that OsmTracker have access to Internet on your phone.

Issue #360 is not related to your bug as Osmtracker use [OsmDroid](https://github.com/osmdroid/osmdroid) to show background maps (and not the URL you point out). I will upgrade osmdroid from version 6.1.5 to 6.1.20, hopefully it can fix your issue 🤞

**Comment by Binnette** [comment]
Ok a new APK with my upgrade is available on the bottom page: https://github.com/labexp/osmtracker-android/actions/runs/12099364732
Download the zip file `debug-20241130-2045` extract it, it contains the APK.

@jer194 can you please install and test this APK (make sure to backup your OsmTracker data before)

**Comment by jer194** [comment]
Cool - it started working again now, thanks a zillion! :-)
Thanks also for fixing the version string (is 2024.11.30-dev).
Upload would go to https://www.openstreetmap.org/.

Phone: Redmi Note 8T (willow),
OS: crDroidAndroid-14.0-20240819-ginkgo-v10.7.zip (Android 14)
