### ISSUE TITLE
Not all photos are exported

### ISSUE THREAD

**Issue by miltonials** [labexp/osmtracker-android#468]
Hi! I was using the application to make some traces, but when I finish the tracking and use the “Export as GPX” option some photos don't appear.

**How to reproduce**
1. Start a new track.
2. Record at least ten or fifteen waypoints with photo.
3. Stop the tracking.
4. Use "Export as GPX" option.
5. Search the exported files.

I tested this using the current development branch, but this also happens using the Google Play version.

**Video**
In this video I have obtained a photo, but it could be different, sometimes more or less photos are exported.

https://github.com/user-attachments/assets/80486416-7e8d-4233-a7f6-ec22607a8b36

**Comment by Binnette** [comment]
Hi @miltonials can you download the "Artifact" zip on the bottom of this page: https://github.com/labexp/osmtracker-android/actions/runs/12136473809

It contains a "dev" apk with a possible fix for your bug. Can you please test it?

**Comment by Andyporras** [comment]
Hi @Binnette, I have just tried the PR #472 that you have uploaded and it does fix the bug correctly.

**Comment by miltonials** [comment]
Hi! You're right @Andyporras I just tested it too and the issue is solved. Thanks @Binnette!

**Comment by miltonials** [comment]
Thank you so much for the quick fix and the kind words!!!😊 I just tested it with the new APK, and everything works perfectly, now all photos are displayed correctly.

**Comment by Binnette** [comment]
#472 merged

**Comment by momu** [comment]
Thanks a lot @Binnette, with the dev build I can use and export pictures again. Are there any reasons not to use the mentioned dev build until a regular release appears?
