### ISSUE TITLE
Should open the keyboard automatically when creating notes

### ISSUE THREAD

**Issue by naoliv** [labexp/osmtracker-android#62]
When clicking the `Notes` button osmtracker doesn't open the keyboard automatically.
For example:

![](http://i.imgur.com/iNhtLuY.png)

It's always necessary to click at the text area to bring up the keyboard.

When creating a note osmtracker should always open the keyboard together, so we can start typing as soon as possible.

**Comment by bjohas** [comment]
+1

**Comment by jidanni** [comment]
Yes I was just going to post a bug: It seems when we want to add a text note, we have to tap an extra time to get the keyboard up so we can type in the note.
Normally the keyboard should be already be ready.

**Comment by aton1698** [comment]
The PR #174 fix this issue, and now is merged! This change (and others) will be available soon in the play store in a beta version.
