### ISSUE TITLE
Feature request: allow gpx tracks to be mailed

### ISSUE THREAD

**Issue by spindr** [labexp/osmtracker-android#84]
Enable gpx tracks to be emailed as attachments.

**Comment by Nokta-strigo** [comment]
As far as I understand, it can be solved as part of #69

**Comment by xsaco07** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow gpx tracks to be mailed](https://trello.com/c/723Kv8rI/52-allow-gpx-tracks-to-be-mailed)

**Comment by jamescr** [comment]
closed with https://github.com/labexp/osmtracker-android/pull/252 and https://github.com/labexp/osmtracker-android/pull/270
