### ISSUE TITLE
Tasker Support

### ISSUE THREAD

**Issue by wartickler** [labexp/osmtracker-android#86]
Would love to be able to kick this off using tasker. Any plans to add support?

**Comment by nguillaumin** [comment]
Hi, no plans, I didn't even know what Tasker was until now :)

**Comment by wartickler** [comment]
Did I miss it?

**Comment by Binnette** [comment]
Tasker seems to be a paid proprietary app. It does not fit the OpenSource spirit of OpenStreetMap.
