### ISSUE TITLE
Cycle map says API key required

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#96]
In settings choose Cycle Map as the tile source. The background of the image seen says API key required.

**Comment by jidanni** [comment]
And choosing MapQuest Open doesn't even show any tiles at all, at least for Taiwan

**Comment by nguillaumin** [comment]
Interesting. I'm using [OSMDroid](https://github.com/osmdroid/osmdroid) for the map background, perhaps something has changed regarding access to the Cycle Map / MapQuest

**Comment by jperryhouts** [comment]
I got the same error, but then I zoomed the map way out and back in to my location and it works fine now.

In my case it was just after I installed the app and it hadn't locked a satellite yet, so it thought I was past the north pole, which also might have been Antarctica for some reason.

**Comment by EmmanuelAB** [comment]
Isn't this issue duplicated of #125 ?

**Comment by jperryhouts** [comment]
If anything that's a duplicate of this issue. It was opened almost a year later than this one.

**Comment by EmmanuelAB** [comment]
Now the app can only use Mapnik as tile provider (since it's the only working without a key). Then Cycle Map is not even choosable. This issue will be closed.
